services:
    data_collector.EzLegacydata:
        class: SRF\Bundles\EzLegacyDebugBundle\DataCollector\EzLegacyDataCollector
        public: false
        arguments: ['@ezpublish_legacy.kernel']
        tags:
            - { name: data_collector, template: "SRFEzLegacyDebugBundle:Collector:ezlegacydata", id: "ezlegacydata" }